version: '2'

services:
  nginx-php-fpm:
    image: mrhuangyuhui/nginx-php-fpm:5.6.31
    restart: always
    ports:
      - "80"
    volumes:
      - /home/byhealth/tangchen:/var/www/html
  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
